package com.kv.lcoptimized.graphs;

import com.kv.lcoptimized.common.Check;

import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * LC 127 · Word Ladder (Hard)                             [was: lc/hard/L50_WordLadder]
 *
 * Pattern : bidirectional BFS - always expand the smaller frontier; stop when frontiers touch.
 *           Neighbours are generated by mutating one letter (26 * L candidates per word).
 * Complexity: O(N * L * 26) worst case, but bidirectional explores ~2 * b^(d/2) instead of b^d.
 * Changed : BUG FIX - the original ADDED endWord to the dictionary, so it found a path even when
 *           endWord wasn't in wordList (the answer must be 0). It also mutated the caller's set.
 *           Upgraded from one-directional BFS.
 *
 * L6/L7 follow-ups: return all shortest paths (LC 126): BFS layer by layer building a parent
 * DAG, then DFS back from end. Huge dictionary -> precompute wildcard buckets "h*t" -> words.
 */
public class LC0127_WordLadder {

    public static int ladderLength(String beginWord, String endWord, List<String> wordList) {
        Set<String> dict = new HashSet<>(wordList);
        if (!dict.contains(endWord)) {
            return 0;
        }
        Set<String> front = new HashSet<>();
        Set<String> back = new HashSet<>();
        front.add(beginWord);
        back.add(endWord);
        dict.remove(beginWord);
        dict.remove(endWord);
        for (int steps = 2; !front.isEmpty(); steps++) {
            if (front.size() > back.size()) {
                Set<String> t = front;
                front = back;
                back = t;
            }
            Set<String> next = new HashSet<>();
            for (String word : front) {
                char[] w = word.toCharArray();
                for (int i = 0; i < w.length; i++) {
                    char original = w[i];
                    for (char c = 'a'; c <= 'z'; c++) {
                        if (c == original) {
                            continue;
                        }
                        w[i] = c;
                        String candidate = new String(w);
                        if (back.contains(candidate)) {
                            return steps;
                        }
                        if (dict.remove(candidate)) {    // remove == mark visited
                            next.add(candidate);
                        }
                    }
                    w[i] = original;
                }
            }
            front = next;
        }
        return 0;
    }

    public static void main(String[] args) {
        List<String> words = Arrays.asList("hot", "dot", "dog", "lot", "log", "cog");
        Check.eq(ladderLength("hit", "cog", words), 5);
        Check.eq(ladderLength("hit", "cog", Arrays.asList("hot", "dot", "dog", "lot", "log")), 0);
        Check.eq(ladderLength("a", "c", Arrays.asList("a", "b", "c")), 2);
    }
}
